package in.grastone.dating.main.enums;

public enum Occupation {
	
	NO_OCCUPATION,
    // Healthcare
    DOCTOR,
    NURSE,
    PHARMACIST,
    DENTIST,
    PHYSICAL_THERAPIST,
    MEDICAL_TECHNICIAN,
    PSYCHOLOGIST,
    RADIOLOGIST,
    OPTOMETRIST,
    PARAMEDIC,

    // Education
    TEACHER,
    SCHOOL_COUNSELOR,
    LIBRARIAN,
    SPECIAL_EDUCATION_TEACHER,
    EDUCATIONAL_ADMINISTRATOR,
    INSTRUCTIONAL_DESIGNER,
    TUTOR,
    PRINCIPAL,
    EDUCATIONAL_CONSULTANT,
    CURRICULUM_DEVELOPER,

    // Technology
    SOFTWARE_DEVELOPER,
    SYSTEMS_ANALYST,
    NETWORK_ADMINISTRATOR,
    CYBERSECURITY_SPECIALIST,
    DATA_SCIENTIST,
    WEB_DEVELOPER,
    IT_SUPPORT_SPECIALIST,
    DATABASE_ADMINISTRATOR,
    UX_UI_DESIGNER,
    CLOUD_ENGINEER,

    // Business and Finance
    ACCOUNTANT,
    FINANCIAL_ANALYST,
    MARKETING_MANAGER,
    HUMAN_RESOURCES_MANAGER,
    SALES_REPRESENTATIVE,
    BUSINESS_CONSULTANT,
    INVESTMENT_BANKER,
    INSURANCE_UNDERWRITER,
    ENTREPRENEUR,
    PROJECT_MANAGER,

    // Creative Arts
    GRAPHIC_DESIGNER,
    PHOTOGRAPHER,
    WRITER_AUTHOR,
    MUSICIAN,
    ACTOR_ACTRESS,
    FILM_DIRECTOR,
    ANIMATOR,
    FASHION_DESIGNER,
    INTERIOR_DESIGNER,
    ART_CURATOR,

    // Engineering
    CIVIL_ENGINEER,
    MECHANICAL_ENGINEER,
    ELECTRICAL_ENGINEER,
    CHEMICAL_ENGINEER,
    AEROSPACE_ENGINEER,
    ENVIRONMENTAL_ENGINEER,
    INDUSTRIAL_ENGINEER,
    SOFTWARE_ENGINEER,
    STRUCTURAL_ENGINEER,
    BIOMEDICAL_ENGINEER,

    // Skilled Trades
    ELECTRICIAN,
    PLUMBER,
    CARPENTER,
    WELDER,
    AUTO_MECHANIC,
    HVAC_TECHNICIAN,
    CONSTRUCTION_MANAGER,
    MASON,
    PAINTER,
    ROOFER,

    // Hospitality and Service
    CHEF,
    WAITSTAFF_SERVER,
    HOTEL_MANAGER,
    TRAVEL_AGENT,
    EVENT_PLANNER,
    BARTENDER,
    CONCIERGE,
    HOUSEKEEPER,
    TOUR_GUIDE,
    CUSTOMER_SERVICE_REPRESENTATIVE,

    // Law and Public Safety
    LAWYER,
    POLICE_OFFICER,
    FIREFIGHTER,
    JUDGE,
    PARALEGAL,
    PROBATION_OFFICER,
    DETECTIVE,
    CORRECTIONAL_OFFICER,
    FORENSIC_SCIENTIST,
    EMERGENCY_MANAGEMENT_SPECIALIST,
    
    OTHER
}
